version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
    - "5433:5432"
    volumes:
    - webflux_data:/var/lib/postgresql/data

volumes:
  webflux_data: