spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/postgres?schema=public
    username: postgres
    password: password
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

server:
  error:
    include-stacktrace: on_param